spring:
  profiles:
    default: dev
  application:
    name: tvbingo
  liquibase:
    default-schema: tvbingo_schema
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%10.10t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: INFO
    com.tvbingo: DEBUG